#!/bin/bash

if [[ "$1" == -r* ]]
then
	echo Average
	
	# Reads every line in file until end of file
	while read line
	do
		sum=0	# Initialize sum that will be updated for each line
		n=0 # total amount of numbers in a row
		
		for number in $line
		do
			sum=$(expr $sum + $number)
			n=$(expr $n + 1)
		done

		echo "$(expr $sum / $n)"	#FIX: Must round
			
	done < $2

elif [[ "$1" == -c* ]]
then
	echo Average

	rows=$(cat $2 | wc -l)
	cols=0
	i=1
	sum=0
	
	read line < $2
	cols=$(echo $line | wc -w)
	(( cols++ ))	
	
	while test $i -ne $cols
	do
		cut -f $i $2 > TMP 

		while read num 
		do 
			sum=$(expr $sum + $num)
		done < TMP		

		echo "$(expr $sum / $rows)" #FIX: MUST ROUND CORRECTLY
		
		sum=0
		i=$(expr $i + 1)
		curr_col=$(expr $curr_col + 1)
	
	done	
	
fi
